apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-alpine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine
          image: alpine:latest
          command: ["sleep", "3600"]  # Keeps the container running
          volumeMounts:
            - name: alpine-storage
              mountPath: /data  # Mount the volume at this path in the container
      volumes:
        - name: alpine-storage
          persistentVolumeClaim:
            claimName: pv-claim  # PVC that was defined earlier
